version : "3.8"
services:
  mysqldb:
    image: mysql:8.0
    container_name: myuserdbcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: myuserdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: user-service-container
    build: .
    image: user-service:1.0 
    command: bash -c 'while !</dev/tcp/mysqldb/3306; do sleep 5; done; node index.js' 
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER_NAME: admin
      DB_USER_PASSWORD: password
      DB_NAME: myuserdb
      DB_CONNECTION_LIMIT: 20
      SERVICE_NAME: user-service
      SERVER_PORT: 3000
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge